[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/employees"
  to = "/employees.html"
  status = 200

[[redirects]]
  from = "/article"
  to = "/article.html"
  status = 200
